In [1]:
import numpy as np
print('numpy: %s' % np.__version__)

import pandas as pd
print('pandas: %s' % pd.__version__)

import tensorflow as tf
print('tensorflow: %s' % tf.__version__)

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
print('sklearn: %s' % sklearn.__version__)

import matplotlib
import matplotlib.pyplot as plt
print('matplotlib: %s' % matplotlib.__version__)

numpy: 1.18.1
pandas: 1.0.1
tensorflow: 2.7.0
sklearn: 1.0.1
matplotlib: 3.1.3

In [2]:
# Display all the columns for the dataframes (not-truncated)
pd.set_option("display.max_columns", None)

In [3]:
#  Import and read the charity_data.csv
application_df = pd.read_csv("Resources/clean_charity_data.csv")
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Split the columns into quantitative and categorical
all_quantitative_columns = set(application_df.describe().columns)
all_categorical_columns = set(application_df.columns) - all_quantitative_columns
print("quantitative columns\n\t" + "\n\t".join(all_quantitative_columns))
print()
print("categorical columns\n\t" + "\n\t".join(all_categorical_columns))

quantitative columns
	IS_SUCCESSFUL
	STATUS
	ASK_AMT

categorical columns
	USE_CASE
	SPECIAL_CONSIDERATIONS
	AFFILIATION
	INCOME_AMT
	CLASSIFICATION
	APPLICATION_TYPE
	ORGANIZATION

In [5]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=all_categorical_columns)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,USE_CASE_CommunityServ,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,CLASSIFICATION_C2100,CLASSIFICATION_C3000,CLASSIFICATION_Other,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust
0,1,5000,1,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
1,1,108590,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,1,5000,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0
3,1,6692,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
4,1,142590,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
34295,1,5000,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0
34296,1,5000,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
34297,1,5000,1,0,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0
34298,1,36500179,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0

In [6]:
# shuffle our data to remove any potential bias
application_df = sklearn.utils.shuffle(application_df)

In [7]:
# Split our preprocessed data into our features and target arrays
target_feature = "IS_SUCCESSFUL"

X = application_df.drop(columns=[target_feature])
y = application_df[target_feature].values.ravel()
print(X.shape, y.shape)

(34299, 43) (34299,)

In [8]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)
print("train\t", X_train.shape, y_train.shape)
print("test\t", X_test.shape, y_test.shape)

train	 (25724, 43) (25724,)
test	 (8575, 43) (8575,)

In [9]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
#Compile, Train and Evaluate the Model

SyntaxError: invalid syntax (<ipython-input-10-9b32969f3a14>, line 1)

In [11]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_shape=(len(X_train_scaled[0]),)
hidden_layers = [
    80, 
    30, 
    1,
]

nn = tf.keras.models.Sequential()
nn.add(tf.keras.Input(shape=input_shape))
for layer in hidden_layers:
    nn.add(tf.keras.layers.Dense(layer))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [12]:
# Compile the model
nn.compile(
    optimizer = "Adam", 
    loss = "mse", 
    metrics = ["mae"]
)

In [13]:
# Train the model
history = nn.fit(
    X_train_scaled, 
    y_train, 
    epochs = 100
)
history.params

Epoch 1/100
804/804 [==============================] - 1s 853us/step - loss: 0.3660 - mae: 0.4202
Epoch 2/100
804/804 [==============================] - 1s 756us/step - loss: 0.2846 - mae: 0.4053
Epoch 3/100
804/804 [==============================] - 1s 763us/step - loss: 0.2151 - mae: 0.3989
Epoch 4/100
804/804 [==============================] - 1s 798us/step - loss: 0.2260 - mae: 0.4002
Epoch 5/100
804/804 [==============================] - 1s 779us/step - loss: 0.2152 - mae: 0.3971
Epoch 6/100
804/804 [==============================] - 1s 740us/step - loss: 0.2047 - mae: 0.3972
Epoch 7/100
804/804 [==============================] - 1s 743us/step - loss: 0.2102 - mae: 0.3982
Epoch 8/100
804/804 [==============================] - 1s 737us/step - loss: 0.2133 - mae: 0.3991
Epoch 9/100
804/804 [==============================] - 1s 790us/step - loss: 0.2015 - mae: 0.3964
Epoch 10/100
804/804 [==============================] - 1s 799us/step - loss: 0.2002 - mae: 0.3961
Epoch 11/100
804/804 [==============================] - 1s 739us/step - loss: 0.2010 - mae: 0.3969
Epoch 12/100
804/804 [==============================] - 1s 742us/step - loss: 0.2004 - mae: 0.3959
Epoch 13/100
804/804 [==============================] - 1s 757us/step - loss: 0.1995 - mae: 0.3961
Epoch 14/100
804/804 [==============================] - 1s 743us/step - loss: 0.1990 - mae: 0.3960
Epoch 15/100
804/804 [==============================] - 1s 745us/step - loss: 0.1989 - mae: 0.3958
Epoch 16/100
804/804 [==============================] - 1s 745us/step - loss: 0.1984 - mae: 0.3955
Epoch 17/100
804/804 [==============================] - 1s 843us/step - loss: 0.1980 - mae: 0.3950
Epoch 18/100
804/804 [==============================] - 1s 807us/step - loss: 0.1983 - mae: 0.3956
Epoch 19/100
804/804 [==============================] - 1s 792us/step - loss: 0.1981 - mae: 0.3954
Epoch 20/100
804/804 [==============================] - 1s 786us/step - loss: 0.1976 - mae: 0.3951
Epoch 21/100
804/804 [==============================] - 1s 777us/step - loss: 0.1981 - mae: 0.3953
Epoch 22/100
804/804 [==============================] - 1s 835us/step - loss: 0.1977 - mae: 0.3954
Epoch 23/100
804/804 [==============================] - 1s 899us/step - loss: 0.1975 - mae: 0.3949
Epoch 24/100
804/804 [==============================] - 1s 992us/step - loss: 0.1977 - mae: 0.3954
Epoch 25/100
804/804 [==============================] - 1s 782us/step - loss: 0.1977 - mae: 0.3949
Epoch 26/100
804/804 [==============================] - 1s 756us/step - loss: 0.1974 - mae: 0.3948
Epoch 27/100
804/804 [==============================] - 1s 750us/step - loss: 0.1975 - mae: 0.3953
Epoch 28/100
804/804 [==============================] - 1s 741us/step - loss: 0.1973 - mae: 0.3946
Epoch 29/100
804/804 [==============================] - 1s 764us/step - loss: 0.1974 - mae: 0.3950
Epoch 30/100
804/804 [==============================] - 1s 731us/step - loss: 0.1973 - mae: 0.3949
Epoch 31/100
804/804 [==============================] - 1s 776us/step - loss: 0.1972 - mae: 0.3947
Epoch 32/100
804/804 [==============================] - 1s 734us/step - loss: 0.1972 - mae: 0.3946
Epoch 33/100
804/804 [==============================] - 1s 785us/step - loss: 0.1971 - mae: 0.3948
Epoch 34/100
804/804 [==============================] - 1s 782us/step - loss: 0.1972 - mae: 0.3945
Epoch 35/100
804/804 [==============================] - 1s 773us/step - loss: 0.1971 - mae: 0.3948
Epoch 36/100
804/804 [==============================] - 1s 746us/step - loss: 0.1972 - mae: 0.3947
Epoch 37/100
804/804 [==============================] - 1s 774us/step - loss: 0.1971 - mae: 0.3946
Epoch 38/100
804/804 [==============================] - 1s 753us/step - loss: 0.1970 - mae: 0.3944
Epoch 39/100
804/804 [==============================] - 1s 746us/step - loss: 0.1970 - mae: 0.3947
Epoch 40/100
804/804 [==============================] - 1s 831us/step - loss: 0.1971 - mae: 0.3948
Epoch 41/100
804/804 [==============================] - 1s 760us/step - loss: 0.1970 - mae: 0.3945
Epoch 42/100
804/804 [==============================] - 1s 735us/step - loss: 0.1971 - mae: 0.3945
Epoch 43/100
804/804 [==============================] - 1s 733us/step - loss: 0.1971 - mae: 0.3944
Epoch 44/100
804/804 [==============================] - 1s 717us/step - loss: 0.1970 - mae: 0.3945
Epoch 45/100
804/804 [==============================] - 1s 729us/step - loss: 0.1969 - mae: 0.3947
Epoch 46/100
804/804 [==============================] - 1s 723us/step - loss: 0.1970 - mae: 0.3942
Epoch 47/100
804/804 [==============================] - 1s 739us/step - loss: 0.1971 - mae: 0.3946
Epoch 48/100
804/804 [==============================] - 1s 729us/step - loss: 0.1969 - mae: 0.3946
Epoch 49/100
804/804 [==============================] - 1s 757us/step - loss: 0.1970 - mae: 0.3943
Epoch 50/100
804/804 [==============================] - 1s 727us/step - loss: 0.1969 - mae: 0.3944
Epoch 51/100
804/804 [==============================] - 1s 734us/step - loss: 0.1968 - mae: 0.3944
Epoch 52/100
804/804 [==============================] - 1s 716us/step - loss: 0.1968 - mae: 0.3937
Epoch 53/100
804/804 [==============================] - 1s 729us/step - loss: 0.1970 - mae: 0.3948
Epoch 54/100
804/804 [==============================] - 1s 721us/step - loss: 0.1969 - mae: 0.3942
Epoch 55/100
804/804 [==============================] - 1s 757us/step - loss: 0.1969 - mae: 0.3942
Epoch 56/100
804/804 [==============================] - 1s 801us/step - loss: 0.1968 - mae: 0.3946
Epoch 57/100
804/804 [==============================] - 1s 779us/step - loss: 0.1968 - mae: 0.3941
Epoch 58/100
804/804 [==============================] - 1s 882us/step - loss: 0.1968 - mae: 0.3945
Epoch 59/100
804/804 [==============================] - 1s 774us/step - loss: 0.1968 - mae: 0.3941
Epoch 60/100
804/804 [==============================] - 1s 732us/step - loss: 0.1968 - mae: 0.3942
Epoch 61/100
804/804 [==============================] - 1s 714us/step - loss: 0.1969 - mae: 0.3942
Epoch 62/100
804/804 [==============================] - 1s 715us/step - loss: 0.1968 - mae: 0.3942
Epoch 63/100
804/804 [==============================] - 1s 706us/step - loss: 0.1969 - mae: 0.3948
Epoch 64/100
804/804 [==============================] - 1s 729us/step - loss: 0.1968 - mae: 0.3938
Epoch 65/100
804/804 [==============================] - 1s 721us/step - loss: 0.1967 - mae: 0.3942 0s - loss: 0.1944 -
Epoch 66/100
804/804 [==============================] - 1s 737us/step - loss: 0.1966 - mae: 0.3939
Epoch 67/100
804/804 [==============================] - 1s 709us/step - loss: 0.1966 - mae: 0.3940
Epoch 68/100
804/804 [==============================] - 1s 712us/step - loss: 0.1967 - mae: 0.3938
Epoch 69/100
804/804 [==============================] - 1s 691us/step - loss: 0.1968 - mae: 0.3947
Epoch 70/100
804/804 [==============================] - 1s 709us/step - loss: 0.1968 - mae: 0.3939
Epoch 71/100
804/804 [==============================] - 1s 707us/step - loss: 0.1967 - mae: 0.3941
Epoch 72/100
804/804 [==============================] - 1s 726us/step - loss: 0.1968 - mae: 0.3944
Epoch 73/100
804/804 [==============================] - 1s 706us/step - loss: 0.1967 - mae: 0.3939
Epoch 74/100
804/804 [==============================] - 1s 714us/step - loss: 0.1967 - mae: 0.3942
Epoch 75/100
804/804 [==============================] - 1s 750us/step - loss: 0.1966 - mae: 0.3938
Epoch 76/100
804/804 [==============================] - 1s 719us/step - loss: 0.1967 - mae: 0.3943
Epoch 77/100
804/804 [==============================] - 1s 719us/step - loss: 0.1966 - mae: 0.3938
Epoch 78/100
804/804 [==============================] - 1s 789us/step - loss: 0.1968 - mae: 0.3943
Epoch 79/100
804/804 [==============================] - 1s 707us/step - loss: 0.1966 - mae: 0.3939
Epoch 80/100
804/804 [==============================] - 1s 772us/step - loss: 0.1966 - mae: 0.3943
Epoch 81/100
804/804 [==============================] - 1s 710us/step - loss: 0.1967 - mae: 0.3939
Epoch 82/100
804/804 [==============================] - 1s 720us/step - loss: 0.1967 - mae: 0.3939
Epoch 83/100

804/804 [==============================] - 1s 734us/step - loss: 0.1967 - mae: 0.3941
Epoch 84/100
804/804 [==============================] - 1s 734us/step - loss: 0.1968 - mae: 0.3945
Epoch 85/100
804/804 [==============================] - 1s 794us/step - loss: 0.1967 - mae: 0.3939
Epoch 86/100
804/804 [==============================] - 1s 763us/step - loss: 0.1966 - mae: 0.3940
Epoch 87/100
804/804 [==============================] - 1s 764us/step - loss: 0.1967 - mae: 0.3943
Epoch 88/100
804/804 [==============================] - 1s 745us/step - loss: 0.1966 - mae: 0.3939
Epoch 89/100
804/804 [==============================] - 1s 715us/step - loss: 0.1966 - mae: 0.3940
Epoch 90/100
804/804 [==============================] - 1s 729us/step - loss: 0.1966 - mae: 0.3933
Epoch 91/100
804/804 [==============================] - 1s 744us/step - loss: 0.1966 - mae: 0.3942
Epoch 92/100
804/804 [==============================] - 1s 735us/step - loss: 0.1968 - mae: 0.3941
Epoch 93/100
804/804 [==============================] - 1s 776us/step - loss: 0.1966 - mae: 0.3941
Epoch 94/100
804/804 [==============================] - 1s 732us/step - loss: 0.1966 - mae: 0.3936
Epoch 95/100
804/804 [==============================] - 1s 727us/step - loss: 0.1966 - mae: 0.3940
Epoch 96/100
804/804 [==============================] - 1s 742us/step - loss: 0.1965 - mae: 0.3939
Epoch 97/100
804/804 [==============================] - 1s 746us/step - loss: 0.1966 - mae: 0.3940
Epoch 98/100
804/804 [==============================] - 1s 759us/step - loss: 0.1966 - mae: 0.3941
Epoch 99/100
804/804 [==============================] - 1s 761us/step - loss: 0.1967 - mae: 0.3942
Epoch 100/100
804/804 [==============================] - 1s 715us/step - loss: 0.1966 - mae: 0.3940

{'verbose': 1, 'epochs': 100, 'steps': 804}

In [14]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.1972 - mae: 0.3934 - 214ms/epoch - 800us/step
Loss: 0.1972220093011856, Accuracy: 0.3933936357498169

In [15]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

In [ ]:
# Load the saved model

In [16]:
loaded_model = tf.keras.models.load_model("AlphabetSoupCharity_Optimization.h5")
# Check its architecture
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [17]:
# Evaluate the loaded model using the test data
model_loss, model_accuracy = loaded_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.1972 - mae: 0.3934 - 191ms/epoch - 714us/step
Loss: 0.1972220093011856, Accuracy: 0.3933936357498169